# 1. Introdução

## Trabalhando com dados

In [ ]:
import pandas as pd
# definir o máximo de linhas e colunas para mostrar pelo pandas
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 10)

In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Python para Data Science/03_funcoes_pacotes_pandas/data/db.csv', sep = ';')

In [ ]:
dataset

,Nome,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
0,Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"['Rodas de liga', 'Travas elétricas', 'Piloto ...",88078.64
1,Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94
2,Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Controle de estabilidad...",72832.16
3,DS5,Motor 2.4 Turbo,2019,NaN,True,"['Travas elétricas', '4 X 4', 'Vidros elétrico...",124549.07
4,Aston Martin DB4,Motor 2.4 Turbo,2006,25757.0,False,"['Rodas de liga', '4 X 4', 'Central multimídia...",92612.10
...,...,...,...,...,...,...,...
253,Phantom 2013,Motor V8,2014,27505.0,False,"['Controle de estabilidade', 'Piloto automátic...",51759.58
254,Cadillac Ciel concept,Motor V8,1991,29981.0,False,"['Bancos de couro', 'Painel digital', 'Sensor ...",51667.06
255,Classe GLK,Motor 5.0 V8 Bi-Turbo,2002,52637.0,False,"['Rodas de liga', 'Controle de tração', 'Câmbi...",68934.03
256,Aston Martin DB5,Motor Diesel,1996,7685.0,False,"['Ar condicionado', '4 X 4', 'Câmbio automátic...",122110.90
257,Macan,Motor Diesel V6,1992,50188.0,False,"['Central multimídia', 'Teto panorâmico', 'Vid...",90381.47

In [ ]:
dataset.dtypes # fornece os tipos de cada coluna

Nome              object
Motor             object
Ano                int64
Quilometragem    float64
Zero_km             bool
Acessórios        object
Valor            float64
dtype: object

In [ ]:
dataset[['Quilometragem', 'Valor']].describe() # fornece um resumo estatístico das variáveis

       Quilometragem          Valor
count     197.000000     258.000000
mean    58278.421320   98960.513101
std     35836.733259   29811.932305
min       107.000000   50742.100000
25%     27505.000000   70743.512500
50%     55083.000000   97724.380000
75%     90495.000000  124633.302500
max    119945.000000  149489.920000

In [ ]:
dataset.info() # mistura as informações de dtypes e describe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 258 entries, 0 to 257
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Nome           258 non-null    object
 1   Motor          258 non-null    object
 2   Ano            258 non-null    int64
 3   Quilometragem  197 non-null    float64
 4   Zero_km        258 non-null    bool
 5   Acessórios     258 non-null    object
 6   Valor          258 non-null    float64
dtypes: bool(1), float64(2), int64(1), object(3)
memory usage: 12.5+ KB

# 2. Tuplas

Tuplas são sequências imutáveis, que são utilizadas para armazenar coleções de itens. É possível criar tuplas de diferentes modos:

  * Colocando os valores entre `( )`

In [ ]:
(1, 2, 3)

(1, 2, 3)

* Separando os itens por `,`

In [ ]:
1, 2, 3

(1, 2, 3)

 * Usando `tuple()`

In [ ]:
tuple([1, 2, 3])

(1, 2, 3)

## Seleções em tuplas

In [ ]:
nomes_carros = ('Jetta Variant', 'Passat', 'Crossfox', 'DSS')
nomes_carros

('Jetta Variant', 'Passat', 'Crossfox', 'DSS')

A seleção em tuplas é igual à seleção em listas.

In [ ]:
nomes_carros[0]

'Jetta Variant'

In [ ]:
nomes_carros[1]

'Passat'

In [ ]:
nomes_carros[-1]

'DSS'

In [ ]:
nomes_carros[1:3] # do mesmo jeito que na lista, o último item não aparece

('Passat', 'Crossfox')

In [ ]:
# incluindo uma tupla dentro de outra
nomes_carros = ('Jetta Variant', 'Passat', 'Crossfox', 'DSS', ('Fusca', 'Gol', 'C4'))
nomes_carros

('Jetta Variant', 'Passat', 'Crossfox', 'DSS', ('Fusca', 'Gol', 'C4'))

In [ ]:
# também é possível selecionar o item de uma tupla dentro de outra
nomes_carros[-1][1]

'Gol'

### Exercício

Em nosso primeiro treinamento de Python para Data Science, nós aprendemos como fazer seleções de itens em listas e em arrays Numpy. O procedimento para seleções em tuplas funciona da mesma forma. Considere a seguinte tupla:

In [ ]:
carros = (
    (
        'Jetta Variant',
        'Motor 4.0 Turbo',
        2003,
        False,
        ('Rodas de liga', 'Travas elétricas', 'Piloto automático')
    ),
    (
        'Passat',
        'Motor Diesel',
        1991,
        True,
        ('Central multimídia', 'Teto panorâmico', 'Freios ABS')
    )
)

Considere também os seguintes códigos de seleção:

 1) `carros[0][3]`

 2) `carros[-1][-1][-1]`

 3) `carros[0][-1][:2]`

Assinale a alternativa que mostra o resultado obtido com os códigos de seleção acima.

## Iterando com tuplas

In [ ]:
nomes_carros = ('Jetta Variant', 'Passat', 'Crossfox', 'DSS')
nomes_carros

('Jetta Variant', 'Passat', 'Crossfox', 'DSS')

In [ ]:
# funciona do mesmo jeito das listas
for item in nomes_carros:
  print(item)

Jetta Variant
Passat
Crossfox
DSS

### Desempacotamento de tuplas

In [ ]:
# posso atribuir cada item a uma variável
carro_1, carro_2, carro_3, carro_4 = nomes_carros
carro_1

'Jetta Variant'

In [ ]:
carro_2

'Passat'

In [ ]:
carro_3

'Crossfox'

In [ ]:
carro_4

'DSS'

In [ ]:
# posso ignorar os itens usando "_"
_, A, _, B = nomes_carros
A

'Passat'

In [ ]:
B

'DSS'

In [ ]:
# posso também usar o * para indicar o restante
_, C, *_ = nomes_carros
C

'Passat'

### `zip()`
Permite associar listas em diferentes tuplas (primeiro elemento com primeiro elemento...)

In [ ]:
carros = ['Jetta Variant', 'Passat', 'Crossfox', 'DS5']
carros

['Jetta Variant', 'Passat', 'Crossfox', 'DS5']

In [ ]:
valores = [88078.64, 106161.94, 72832.16, 124549.07]
valores

[88078.64, 106161.94, 72832.16, 124549.07]

In [ ]:
list(zip(carros, valores))

[('Jetta Variant', 88078.64),
 ('Passat', 106161.94),
 ('Crossfox', 72832.16),
 ('DS5', 124549.07)]

In [ ]:
for carro, valor in zip(carros, valores):
  print(f'O carro {carro} custa {valor}.')

O carro Jetta Variant custa 88078.64.
O carro Passat custa 106161.94.
O carro Crossfox custa 72832.16.
O carro DS5 custa 124549.07.

In [ ]:
for carro, valor in zip(carros, valores):
  if valor > 100000:
    print(f'O carro {carro} custa mais de 100 mil')

O carro Passat custa mais de 100 mil
O carro DS5 custa mais de 100 mil

### Exercício 1

O procedimento de iteração em tuplas é o mesmo que aprendemos com listas, no treinamento anterior. Utilizamos a tupla como iterador de um laço `for` simples, ou aninhado, e conseguimos acesso a cada item individualmente.

Para responder esta questão, considere a mesma tupla da atividade anterior:

In [1]:
carros = (
    (
        'Jetta Variant',
        'Motor 4.0 Turbo',
        2003,
        False,
        ('Rodas de liga', 'Travas elétricas', 'Piloto automático')
    ),
    (
        'Passat',
        'Motor Diesel',
        1991,
        True,
        ('Central multimídia', 'Teto panorâmico', 'Freios ABS')
    )
)

Observe que se trata de uma tupla (1º nível) com duas tuplas, que representam um conjunto de dados de dois veículos (2º nível), e que uma destas informações (acessórios) vêm também dentro de uma tupla (3º nível). O que precisamos é iterar na tupla `carros` e imprimir **todos os acessórios** que aparecem. O resultado desejado é o seguinte:

```
Rodas de liga
Travas elétricas
Piloto automático
Central multimídia
Teto panorâmico
Freios ABS
```

In [4]:
# resposta
for carro in carros:
  for item in carro[-1]:
    print(item)

Rodas de liga
Travas elétricas
Piloto automático
Central multimídia
Teto panorâmico
Freios ABS

### Exercício 2

Duas ferramentas bastante utilizadas quando iteramos com tuplas são o desempacotamento de tuplas e a built-in function `zip()`.

Com o desempacotamento de tuplas, é possível fazer declarações conjuntas de variáveis e utilizar cada variável individualmente. Por exemplo:

```nome, valor = ('Passat', 100000.0) ```

A função `zip()` permite gerar um iterador de tuplas, como no exemplo abaixo:

```
nomes = ['Passat', 'Crossfox']
valores = [100000.0, 75000.0]
list(zip(nomes, valores))

# out
[('Passat', 100000.0), ('Crossfox', 75000.0)]
```

Considerando as duas listas abaixo:

In [5]:
nomes = ['Passat', 'Crossfox', 'DS5', 'C4', 'Jetta']
kms = [15000, 12000, 32000, 8000, 50000]

E utilizando o ferramental apresentado acima, marque a alternativa com o código que possibilita a impressão dos nomes dos veículos com quilometragem abaixo de 20.000 km.

In [8]:
for carro, km in zip(nomes, kms): # notar que não é necessário usar o list, já que não preciso visualizar
  if km < 20000:
    print(carro)

Passat
Crossfox
C4

# 3. Dicionários

## Criando dicionários

Os dicionários são estruturas de informações em que há sempre um dado primário (chave) e dados secundários (valores)

In [9]:
carros = ['Jetta Variant', 'Passat', 'Crossfox']
carros

['Jetta Variant', 'Passat', 'Crossfox']

In [10]:
valores = [88078.64, 106161.94, 72832.16]
valores

[88078.64, 106161.94, 72832.16]

Exemplo de como trabalhar selecionando valores a partir de uma lista:

In [11]:
# primeiro, identificamos qual é o índice
carros.index('Passat')

1

In [12]:
# então, para sabr qual é o valor do Passat
valores[carros.index('Passat')]

106161.94

Usando um dicionário, esse processo é mais fácil

In [13]:
# construindo o dicionário manualmente
dados = {'Jetta Variant':88078.64, 'Passat':106161.94, 'Crossfox':72832.16}
dados

{'Crossfox': 72832.16, 'Jetta Variant': 88078.64, 'Passat': 106161.94}

In [14]:
type(dados)

dict

## Usando `zip()` para criar dicionários

Com o zip, a gente conseguia criar uma lista de tuplas combinando `list(zip())`

In [15]:
list(zip(carros, valores))

[('Jetta Variant', 88078.64), ('Passat', 106161.94), ('Crossfox', 72832.16)]

Podemos criar dicionários de maneira semelhante, associando `dict()`

In [16]:
dict(zip(carros, valores))

{'Crossfox': 72832.16, 'Jetta Variant': 88078.64, 'Passat': 106161.94}

### Exercício

Vimos em nossa última aula algumas maneiras de se criar um dicionário.

Tendo como base as duas listas abaixo:

In [17]:
nomes = ['Passat', 'Crossfox', 'DS5', 'C4', 'Jetta']
kms = [15000, 12000, 32000, 8000, 50000]

Marque a alternativa que mostra uma das formas de se criar dicionários a partir de listas.

In [18]:
dict(zip(nomes, kms))

{'C4': 8000, 'Crossfox': 12000, 'DS5': 32000, 'Jetta': 50000, 'Passat': 15000}

## Operações com dicionários

In [34]:
dados = {'Jetta Variant':88078.64, 'Passat':106161.94, 'Crossfox':72832.16}
dados

{'Crossfox': 72832.16, 'Jetta Variant': 88078.64, 'Passat': 106161.94}

### Valor da chave - `dict[key]`
Retorna o valor referente à chave fornecida

In [25]:
dados['Passat']

106161.94

### Chave está no dicionário? `key in dict`
Identifica se a chave está no dicionário

In [26]:
'Passat' in dados

True

In [23]:
'Gol' in dados

False

In [24]:
'Gol' not in dados

True

### Tamanho do dicionário - `len(dict)`
Retorna o tamanho do dicionário (número de chaves)

In [27]:
len(dados)

3

### Inclui novo item - `dict[newkey] = newvalue`
Inclui novo valor no dicionário

In [35]:
dados['DS5'] = 124549.07
dados

{'Crossfox': 72832.16,
 'DS5': 124549.07,
 'Jetta Variant': 88078.64,
 'Passat': 106161.94}

### Remover item - `del dict[key]`
Remove item do dicionário

In [36]:
dados

{'Crossfox': 72832.16,
 'DS5': 124549.07,
 'Jetta Variant': 88078.64,
 'Passat': 106161.94}

In [37]:
del dados['Passat']
dados

{'Crossfox': 72832.16, 'DS5': 124549.07, 'Jetta Variant': 88078.64}

### Exercício

Utilize o dicionário `dados` para responder a questão:

In [39]:
dados = {
    'Passat': {
        'ano': 2012,
        'km': 50000,
        'valor': 75000,
        'acessorios': ['Airbag', 'ABS']
    }, 
    'Crossfox': {
        'ano': 2015,
        'km': 35000,
        'valor': 25000
    }
}

Note que `dados` tem dois itens, onde a chave (*key*) é o nome do veículo e o valor (*value*) é um dicionário com informações sobre este veículo (ano, quilometragem, valor e acessórios). Nossa tarefa nesta atividade é aprender como acessar as informações de um dicionário dentro de outro dicionário.

Queremos o seguinte:

1) Testar se a chave `acessorios` existe no dicionário de informações do carro Crossfox (Resposta: `False`)

In [40]:
'acessorios' in dados['Crossfox']

False

2) Testar se a chave `acessorios` existe no dicionário de informações do carro Passat (Resposta: `True`)

In [41]:
'acessorios' in dados['Passat']

True

3) Obter o valor do carro `Crossfox` (Resposta: `25000`)

In [42]:
dados['Crossfox']['valor']

25000

4) Acessar o último acessório do carro `Passat` (Resposta: `'ABS'`)

In [43]:
dados['Passat']['acessorios'][-1]

'ABS'

## Métodos de dicionários

In [44]:
dados = {'Crossfox': 72832.16, 'DS5': 124549.07, 'Jetta Variant': 88078.64}
dados

{'Crossfox': 72832.16, 'DS5': 124549.07, 'Jetta Variant': 88078.64}

### Atualiza o dictionário - `dict.update()`

In [45]:
# posso adicionar um novo item
dados.update({'Passat': 106161.94})
dados

{'Crossfox': 72832.16,
 'DS5': 124549.07,
 'Jetta Variant': 88078.64,
 'Passat': 106161.94}

In [46]:
# posso atualizar o valor de algum item
dados.update({'Passat': 106161.96})
dados

{'Crossfox': 72832.16,
 'DS5': 124549.07,
 'Jetta Variant': 88078.64,
 'Passat': 106161.96}

In [47]:
# posso atualizar e adicionar ao mesmo tempo
dados.update({'Passat': 106161.95, 'Fusca': 150000})
dados

{'Crossfox': 72832.16,
 'DS5': 124549.07,
 'Fusca': 150000,
 'Jetta Variant': 88078.64,
 'Passat': 106161.95}

### Criar cópia - `dict.copy()`
Se eu apenas usar `dadosCopy = dados`, eu vou apenas alterar o rótulo para uma mesma variável. Então eu preciso fazer sempre a cópia, se eu quiser fazer alterações em uma variável e não alterar a original.

In [49]:
dadosCopy = dados.copy()
dadosCopy

{'Crossfox': 72832.16,
 'DS5': 124549.07,
 'Fusca': 150000,
 'Jetta Variant': 88078.64,
 'Passat': 106161.95}

In [50]:
del dadosCopy['Fusca']
dadosCopy

{'Crossfox': 72832.16,
 'DS5': 124549.07,
 'Jetta Variant': 88078.64,
 'Passat': 106161.95}

In [51]:
dados

{'Crossfox': 72832.16,
 'DS5': 124549.07,
 'Fusca': 150000,
 'Jetta Variant': 88078.64,
 'Passat': 106161.95}

### Retorna valor e remove chave - `dict.pop(key)`

In [52]:
dadosCopy

{'Crossfox': 72832.16,
 'DS5': 124549.07,
 'Jetta Variant': 88078.64,
 'Passat': 106161.95}

In [53]:
dadosCopy.pop('Passat')

106161.95

In [54]:
dadosCopy

{'Crossfox': 72832.16, 'DS5': 124549.07, 'Jetta Variant': 88078.64}

É possível fazer com que o método retorne uma mensagem de erro se não encontrar a chave

In [55]:
dadosCopy.pop('Passat', 'Chave não encontrada')

'Chave não encontrada'

In [56]:
dadosCopy.pop('DS5', 'Chave não encontrada')

124549.07

In [57]:
dadosCopy

{'Crossfox': 72832.16, 'Jetta Variant': 88078.64}

### Remover todos os itens - `dict.clear()`

In [58]:
dadosCopy.clear()
dadosCopy

{}

### Exercício
Considere o dicionário abaixo:

In [59]:
dados = {'Jetta': 88000, 'Crossfox': 72000, 'DS5': 124000}

## Iterando em dicionários

In [63]:
dados = {'Crossfox': 72832.16,
 'DS5': 124549.07,
 'Fusca': 150000,
 'Jetta Variant': 88078.64,
 'Passat': 106161.95}
dados

{'Crossfox': 72832.16,
 'DS5': 124549.07,
 'Fusca': 150000,
 'Jetta Variant': 88078.64,
 'Passat': 106161.95}

### Lista de chaves - `dict.keys()`

In [64]:
dados.keys()

dict_keys(['Crossfox', 'DS5', 'Fusca', 'Jetta Variant', 'Passat'])

In [65]:
for key in dados.keys():
  print(dados[key])

72832.16
124549.07
150000
88078.64
106161.95

### Lista de valores - `dict.values()`

In [67]:
dados.values()

dict_values([72832.16, 124549.07, 150000, 88078.64, 106161.95])

### Converte em tupla - `dict.items()`

In [68]:
dados.items()

dict_items([('Crossfox', 72832.16), ('DS5', 124549.07), ('Fusca', 150000), ('Jetta Variant', 88078.64), ('Passat', 106161.95)])

In [69]:
for item in dados.items():
  print(item)

('Crossfox', 72832.16)
('DS5', 124549.07)
('Fusca', 150000)
('Jetta Variant', 88078.64)
('Passat', 106161.95)

In [73]:
for key, value in dados.items():
  if value < 100000:
    print(key)

Crossfox
Jetta Variant

### Exercício

In [74]:
dados = {
    'Crossfox': {'valor': 72000, 'ano': 2005}, 
    'DS5': {'valor': 125000, 'ano': 2015}, 
    'Fusca': {'valor': 150000, 'ano': 1976}, 
    'Jetta': {'valor': 88000, 'ano': 2010}, 
    'Passat': {'valor': 106000, 'ano': 1998}
}

Selecione a alternativa que apresenta o código que imprime somente os nomes dos veículos com ano de fabricação maior ou igual a 2000.

In [86]:
for carro in dados.keys():  
  if dados[carro]['ano'] >= 2000:
    print(carro)

Crossfox
DS5
Jetta

In [88]:
for item in dados.items():
  if item[1]['ano'] >= 2000:
    print(item[0])

Crossfox
DS5
Jetta

# 4. Funções e pacotes

## Built-in function

In [1]:
dados = {'Jetta Variant': 88078.64, 'Passat': 106161.94, 'Crossfox': 72832.16}
dados

{'Crossfox': 72832.16, 'Jetta Variant': 88078.64, 'Passat': 106161.94}

In [4]:
valores = []
for valor in dados.values():
  valores.append(valor)
valores

[88078.64, 106161.94, 72832.16]

In [5]:
list(dados.values())

[88078.64, 106161.94, 72832.16]

In [3]:
soma = 0
for valor in dados.values():
  soma += valor
soma

267072.74

In [6]:
sum(dados.values())

267072.74

## Definindo funções sem e com parâmetros

### sem parâmetro

In [9]:
def media():
  valor = (1 + 2 + 3) / 3
  print(valor)

media()

2.0

### com parâmetro

In [10]:
def media(number_1, number_2, number_3):
  valor = (number_1 + number_2 + number_3) / 3
  print(valor)

In [11]:
media(1, 2 ,3)

2.0

In [12]:
media(23, 45, 67)

45.0

In [13]:
def media(lista):
  valor = sum(lista) / len(lista)
  print(valor)

In [15]:
resultado = media([1, 2, 3, 4, 5, 6, 7, 8, 9])

5.0

Como dentro da função o valor não é retornado, apenas "impresso", resultado não recebe o valor final do cálculo

In [16]:
type(resultado)

NoneType

### Exercício
Uma tarefa importante em um trabalho de cientista de dados é o tratamento do dataset que vamos utilizar. Essa tarefa é dividida em várias etapas e uma delas é a sumarização dos dados, onde obtemos estatísticas descritivas para ajudar nas tomadas de decisão.

Algumas sumarizações precisam de um conjunto de elaborações, que devem ser desenvolvidas pelo próprio pesquisador. Neste ponto, as funções são bastante úteis no trabalho do cientista de dados. Com elas, podemos definir um conjunto de tarefas específicas, que recebem entradas e retornam resultados, e reutilizar esta codificação em outras partes de nosso projeto.

Um exemplo disso em nosso projeto é o cálculo da quilometragem média que um veículo rodou por ano. Não existe uma função pronta para o cálculo desta estatística em Python, e por isso precisamos escrever uma função que obtenha este valor.

Considere o conjunto de informações abaixo para responder o problema:

In [17]:
dados = {
    'Crossfox': {'km': 35000, 'ano': 2005}, 
    'DS5': {'km': 17000, 'ano': 2015}, 
    'Fusca': {'km': 130000, 'ano': 1979}, 
    'Jetta': {'km': 56000, 'ano': 2011}, 
    'Passat': {'km': 62000, 'ano': 1999}
}

A estrutura a seguir é a definição de uma função que obtém e imprime a quilometragem média anual de cada veículo em um dicionário com a estrutura do dicionário dados acima:

In [18]:
def km_media(dataset, ano_atual):
    for item in dataset.items():
        result = item[1]['km'] / (ano_atual - item[1]['ano'])
        print(result)

In [19]:
km_media(dados, 2019)

2500.0
4250.0
3250.0
7000.0
3100.0

## Definindo funções que retornam valores

In [20]:
def media(lista):
  valor = sum(lista) / len(lista)
  return valor

In [21]:
resultado = media([1, 2, 3, 4, 5, 6, 7, 8, 9])
resultado

5.0

## Definindo funções que retornam mais de um valor

In [23]:
def media(lista):
  valor = sum(lista) / len(lista)
  return (valor, len(lista))

media([1, 2, 3, 4, 5, 6, 7, 8, 9])

(5.0, 9)

## Exercício
No problema anterior, definimos uma função para obter a quilometragem média anual de cada veículo em um dataset. Precisamos melhorar um pouco a nossa função e obter valores que possam ser reutilizados em outras partes do nosso projeto.

Aprendemos em nosso último vídeo como criar funções que retornam valores, e é isso que precisamos para resolver este problema. A estrutura a seguir é a definição de uma função que calcula as quilometragens médias anuais de cada veículo e retorna um dicionário com os nomes dos veículos como chaves e as quilometragens médias como valores:

In [24]:
dados = {
    'Crossfox': {'km': 35000, 'ano': 2005}, 
    'DS5': {'km': 17000, 'ano': 2015}, 
    'Fusca': {'km': 130000, 'ano': 1979}, 
    'Jetta': {'km': 56000, 'ano': 2011}, 
    'Passat': {'km': 62000, 'ano': 1999}
}

In [30]:
def km_media(dataset, ano_atual):
    result = {}
    for item in dataset.items():
        media = item[1]['km'] / (ano_atual - item[1]['ano'])
        result.update({item[0]: result})
    return result

In [29]:
km_media(dados, 2019)

{'Crossfox': 2500.0,
 'DS5': 4250.0,
 'Fusca': 3250.0,
 'Jetta': 7000.0,
 'Passat': 3100.0}

A nossa função `km_media()` já retorna valores que podem ser trabalhados em outras partes do nosso projeto. Uma elaboração extra, que também pode ser interessante, principalmente para a criação de DataFrames (próximas aulas), é a atualização do próprio `input` da função. Podemos fazer com que a nossa função retorne as informações do dicionário dados, incluindo as informações de quilometragem média anual.

A estrutura a seguir é a definição de uma função que calcula as quilometragens médias anuais de cada veículo, atualiza o dicionário de entrada e retorna este dicionário:

In [31]:
dados = {
    'Crossfox': {'km': 35000, 'ano': 2005}, 
    'DS5': {'km': 17000, 'ano': 2015}, 
    'Fusca': {'km': 130000, 'ano': 1979}, 
    'Jetta': {'km': 56000, 'ano': 2011}, 
    'Passat': {'km': 62000, 'ano': 1999}
}

In [32]:
def km_media(dataset, ano_atual):
    result = {}
    for item in dataset.items():
        media = item[1]['km'] / (ano_atual - item[1]['ano'])
        item[1].update({'km_media': media})
        result.update({item[0]: item[1]})
    return result

# 5. Básico de Pandas

In [33]:
import pandas as pd

**Series** são arrays unidimensionais rotulados capazes de armazenar qualquer tipo de dado.

`s = pd.Series(dados, index = index)`

**Dataframes** também são dados estruturados, mas bidimensionais, com rótulos nas linhas e colunas.

`df = pd.DataFrame(dados, index = index, columns = columns)`

O argumento `dados` pode ser uma lista, um dicionário, uma array NumPy, ou outra Series ou Dataframe.

## Estrutura de dados

### Criando uma Series a partir de uma lista

In [35]:
carros = ['Jetta Variant', 'Passat', 'Crossfox']
carros

['Jetta Variant', 'Passat', 'Crossfox']

In [36]:
pd.Series(carros)

0    Jetta Variant
1           Passat
2         Crossfox
dtype: object

### Criando um DataFrame a partir de uma lista de dicionários

In [37]:
dados = [
    {'Nome': 'Jetta Variant', 'Motor': 'Motor 4.0 Turbo', 'Ano': 2003, 'Quilometragem': 44410.0, 'Zero_km': False, 'Valor': 88078.64},
    {'Nome': 'Passat', 'Motor': 'Motor Diesel', 'Ano': 1991, 'Quilometragem': 5712.0, 'Zero_km': False, 'Valor': 106161.94},
    {'Nome': 'Crossfox', 'Motor': 'Motor Diesel V8', 'Ano': 1990, 'Quilometragem': 37123.0, 'Zero_km': False, 'Valor': 72832.16}
]

In [38]:
dataset = pd.DataFrame(dados)

In [39]:
dataset

            Nome            Motor   Ano  Quilometragem  Zero_km      Valor
0  Jetta Variant  Motor 4.0 Turbo  2003        44410.0    False   88078.64
1         Passat     Motor Diesel  1991         5712.0    False  106161.94
2       Crossfox  Motor Diesel V8  1990        37123.0    False   72832.16

In [41]:
# para alterar a ordem das colunas
dataset[['Nome', 'Ano', 'Motor', 'Quilometragem', 'Zero_km', 'Valor']]

            Nome   Ano            Motor  Quilometragem  Zero_km      Valor
0  Jetta Variant  2003  Motor 4.0 Turbo        44410.0    False   88078.64
1         Passat  1991     Motor Diesel         5712.0    False  106161.94
2       Crossfox  1990  Motor Diesel V8        37123.0    False   72832.16

### Criando um DataFrame a partir de um dicionário

In [43]:
dados = {
    'Nome': ['Jetta Variant', 'Passat', 'Crossfox'], 
    'Motor': ['Motor 4.0 Turbo', 'Motor Diesel', 'Motor Diesel V8'],
    'Ano': [2003, 1991, 1990],
    'Quilometragem': [44410.0, 5712.0, 37123.0],
    'Zero_km': [False, False, False],
    'Valor': [88078.64, 106161.94, 72832.16]
}

In [45]:
dataset = pd.DataFrame(dados)
dataset

            Nome            Motor   Ano  Quilometragem  Zero_km      Valor
0  Jetta Variant  Motor 4.0 Turbo  2003        44410.0    False   88078.64
1         Passat     Motor Diesel  1991         5712.0    False  106161.94
2       Crossfox  Motor Diesel V8  1990        37123.0    False   72832.16

### Criando a partir de um arquivo externo

In [69]:
dataset = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Python para Data Science/03_pandas/data/db.csv', 
                      sep = ';', index_col = 'Nome')
dataset

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"['Rodas de liga', 'Travas elétricas', 'Piloto ...",88078.64
Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94
Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Controle de estabilidad...",72832.16
DS5,Motor 2.4 Turbo,2019,NaN,True,"['Travas elétricas', '4 X 4', 'Vidros elétrico...",124549.07
Aston Martin DB4,Motor 2.4 Turbo,2006,25757.0,False,"['Rodas de liga', '4 X 4', 'Central multimídia...",92612.10
...,...,...,...,...,...,...
Phantom 2013,Motor V8,2014,27505.0,False,"['Controle de estabilidade', 'Piloto automátic...",51759.58
Cadillac Ciel concept,Motor V8,1991,29981.0,False,"['Bancos de couro', 'Painel digital', 'Sensor ...",51667.06
Classe GLK,Motor 5.0 V8 Bi-Turbo,2002,52637.0,False,"['Rodas de liga', 'Controle de tração', 'Câmbi...",68934.03
Aston Martin DB5,Motor Diesel,1996,7685.0,False,"['Ar condicionado', '4 X 4', 'Câmbio automátic...",122110.90
Macan,Motor Diesel V6,1992,50188.0,False,"['Central multimídia', 'Teto panorâmico', 'Vid...",90381.47

### Exercício

In [50]:
dados = {
    'Crossfox': {'km': 35000, 'ano': 2005}, 
    'DS5': {'km': 17000, 'ano': 2015}, 
    'Fusca': {'km': 130000, 'ano': 1979}, 
    'Jetta': {'km': 56000, 'ano': 2011}, 
    'Passat': {'km': 62000, 'ano': 1999}
}

In [52]:
def km_media(dataset, ano_atual):
    result = {}
    for item in dataset.items():
        media = item[1]['km'] / (ano_atual - item[1]['ano'])
        item[1].update({ 'km_media': media })
        result.update({ item[0]: item[1] })

    return result

km_media(dados, 2019)

{'Crossfox': {'ano': 2005, 'km': 35000, 'km_media': 2500.0},
 'DS5': {'ano': 2015, 'km': 17000, 'km_media': 4250.0},
 'Fusca': {'ano': 1979, 'km': 130000, 'km_media': 3250.0},
 'Jetta': {'ano': 2011, 'km': 56000, 'km_media': 7000.0},
 'Passat': {'ano': 1999, 'km': 62000, 'km_media': 3100.0}}

In [58]:
pd.DataFrame(km_media(dados, 2019)).T

                km     ano  km_media
Crossfox   35000.0  2005.0    2500.0
DS5        17000.0  2015.0    4250.0
Fusca     130000.0  1979.0    3250.0
Jetta      56000.0  2011.0    7000.0
Passat     62000.0  1999.0    3100.0

## Seleções com DataFrames

In [59]:
dataset.head()

,Nome,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
0,Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"['Rodas de liga', 'Travas elétricas', 'Piloto ...",88078.64
1,Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94
2,Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Controle de estabilidad...",72832.16
3,DS5,Motor 2.4 Turbo,2019,NaN,True,"['Travas elétricas', '4 X 4', 'Vidros elétrico...",124549.07
4,Aston Martin DB4,Motor 2.4 Turbo,2006,25757.0,False,"['Rodas de liga', '4 X 4', 'Central multimídia...",92612.10

### Selecionando colunas

In [60]:
dataset['Valor']

0       88078.64
1      106161.94
2       72832.16
3      124549.07
4       92612.10
         ...
253     51759.58
254     51667.06
255     68934.03
256    122110.90
257     90381.47
Name: Valor, Length: 258, dtype: float64

In [61]:
type(dataset['Valor']) # note que desse modo ele retorna uma Series

pandas.core.series.Series

In [62]:
dataset[['Valor']]

         Valor
0     88078.64
1    106161.94
2     72832.16
3    124549.07
4     92612.10
..         ...
253   51759.58
254   51667.06
255   68934.03
256  122110.90
257   90381.47

[258 rows x 1 columns]

In [63]:
type(dataset[['Valor']]) # com dois colchetes ele retorna um dataframe

pandas.core.frame.DataFrame

### Selecionando linhas

In [64]:
dataset[1:4]

,Nome,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
1,Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94
2,Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Controle de estabilidad...",72832.16
3,DS5,Motor 2.4 Turbo,2019,NaN,True,"['Travas elétricas', '4 X 4', 'Vidros elétrico...",124549.07

### Utilizando `.loc`
Retorna o valor a partir da chave fornecida. É importante garantir que o dado está estruturado com a chave que vai ser utilizada.

In [70]:
dataset.loc['Passat'] # um colchete retorna Series, dois retorna DataFrame

Motor                                                 Motor Diesel
Ano                                                           1991
Quilometragem                                               5712.0
Zero_km                                                      False
Acessórios       ['Central multimídia', 'Teto panorâmico', 'Fre...
Valor                                                    106161.94
Name: Passat, dtype: object

In [71]:
dataset.loc[['Passat', 'Crossfox']]

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94
Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Controle de estabilidad...",72832.16

### Utilizanto `.iloc[]`
Retorna o valor a partir do índice (localização fornecida)

In [74]:
dataset.head()

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"['Rodas de liga', 'Travas elétricas', 'Piloto ...",88078.64
Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94
Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Controle de estabilidad...",72832.16
DS5,Motor 2.4 Turbo,2019,NaN,True,"['Travas elétricas', '4 X 4', 'Vidros elétrico...",124549.07
Aston Martin DB4,Motor 2.4 Turbo,2006,25757.0,False,"['Rodas de liga', '4 X 4', 'Central multimídia...",92612.10

In [73]:
dataset.iloc[[1]]

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94

In [75]:
dataset.iloc[1:4, [0,5,2]] # funciona do mesmo jeito dos arrays

                    Motor      Valor  Quilometragem
Nome
Passat       Motor Diesel  106161.94         5712.0
Crossfox  Motor Diesel V8   72832.16        37123.0
DS5       Motor 2.4 Turbo  124549.07            NaN

### Exercício

In [76]:
import pandas as pd

dados = {
    'Nome': ['Jetta', 'Passat', 'Crossfox', 'DS5', 'Fusca'], 
    'Motor': ['Motor 4.0 Turbo', 'Motor Diesel', 'Motor Diesel V8', 'Motor 2.0', 'Motor 1.6'],
    'Ano': [2019, 2003, 1991, 2019, 1990],
    'Quilometragem': [0.0, 5712.0, 37123.0, 0.0, 120000.0],
    'Zero_km': [True, False, False, True, False],
    'Valor': [88000.0, 106000.0, 72000.0, 89000.0, 32000.0]
}

dataset = pd.DataFrame(dados)

In [79]:
dataset[['Nome', 'Ano', 'Quilometragem', 'Valor']][1:3]

       Nome   Ano  Quilometragem     Valor
1    Passat  2003         5712.0  106000.0
2  Crossfox  1991        37123.0   72000.0

### Exercício 2

In [82]:
import pandas as pd

dados = {
    'Motor': ['Motor 4.0 Turbo', 'Motor Diesel', 'Motor Diesel V8', 'Motor 2.0', 'Motor 1.6'],
    'Ano': [2019, 2003, 1991, 2019, 1990],
    'Quilometragem': [0.0, 5712.0, 37123.0, 0.0, 120000.0],
    'Zero_km': [True, False, False, True, False],
    'Valor': [88000.0, 106000.0, 72000.0, 89000.0, 32000.0]
}

dataset = pd.DataFrame(dados, index = ['Jetta', 'Passat', 'Crossfox', 'DS5', 'Fusca'])
dataset

                    Motor   Ano  Quilometragem  Zero_km     Valor
Jetta     Motor 4.0 Turbo  2019            0.0     True   88000.0
Passat       Motor Diesel  2003         5712.0    False  106000.0
Crossfox  Motor Diesel V8  1991        37123.0    False   72000.0
DS5             Motor 2.0  2019            0.0     True   89000.0
Fusca           Motor 1.6  1990       120000.0    False   32000.0

In [81]:
dataset.loc[['Passat', 'DS5'], ['Motor', 'Valor']]

               Motor     Valor
Passat  Motor Diesel  106000.0
DS5        Motor 2.0   89000.0

In [83]:
dataset.iloc[[1,3], [0,-1]]

               Motor     Valor
Passat  Motor Diesel  106000.0
DS5        Motor 2.0   89000.0

## Queries com Dataframes

In [84]:
dataset = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Python para Data Science/03_pandas/data/db.csv', 
                      sep = ';', index_col = 'Nome')
dataset

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"['Rodas de liga', 'Travas elétricas', 'Piloto ...",88078.64
Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94
Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Controle de estabilidad...",72832.16
DS5,Motor 2.4 Turbo,2019,NaN,True,"['Travas elétricas', '4 X 4', 'Vidros elétrico...",124549.07
Aston Martin DB4,Motor 2.4 Turbo,2006,25757.0,False,"['Rodas de liga', '4 X 4', 'Central multimídia...",92612.10
...,...,...,...,...,...,...
Phantom 2013,Motor V8,2014,27505.0,False,"['Controle de estabilidade', 'Piloto automátic...",51759.58
Cadillac Ciel concept,Motor V8,1991,29981.0,False,"['Bancos de couro', 'Painel digital', 'Sensor ...",51667.06
Classe GLK,Motor 5.0 V8 Bi-Turbo,2002,52637.0,False,"['Rodas de liga', 'Controle de tração', 'Câmbi...",68934.03
Aston Martin DB5,Motor Diesel,1996,7685.0,False,"['Ar condicionado', '4 X 4', 'Câmbio automátic...",122110.90
Macan,Motor Diesel V6,1992,50188.0,False,"['Central multimídia', 'Teto panorâmico', 'Vid...",90381.47

In [85]:
dataset.Motor

Nome
Jetta Variant                  Motor 4.0 Turbo
Passat                            Motor Diesel
Crossfox                       Motor Diesel V8
DS5                            Motor 2.4 Turbo
Aston Martin DB4               Motor 2.4 Turbo
                                 ...
Phantom 2013                          Motor V8
Cadillac Ciel concept                 Motor V8
Classe GLK               Motor 5.0 V8 Bi-Turbo
Aston Martin DB5                  Motor Diesel
Macan                          Motor Diesel V6
Name: Motor, Length: 258, dtype: object

In [86]:
dataset.Motor == 'Motor Diesel'

Nome
Jetta Variant            False
Passat                    True
Crossfox                 False
DS5                      False
Aston Martin DB4         False
                         ...
Phantom 2013             False
Cadillac Ciel concept    False
Classe GLK               False
Aston Martin DB5          True
Macan                    False
Name: Motor, Length: 258, dtype: bool

In [87]:
select = dataset.Motor == 'Motor Diesel'

In [88]:
dataset[select]

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94
Effa Hafei Picape Baú,Motor Diesel,1991,102959.0,False,"['Controle de estabilidade', 'Painel digital',...",125684.65
Sorento,Motor Diesel,2019,NaN,True,"['Sensor de chuva', 'Câmera de estacionamento'...",81399.35
New Fiesta Hatch,Motor Diesel,2017,118895.0,False,"['Sensor de estacionamento', 'Travas elétricas...",66007.16
Kangoo Express,Motor Diesel,2007,29132.0,False,"['Bancos de couro', 'Câmbio automático', 'Pilo...",146716.91
Fit,Motor Diesel,2013,44329.0,False,"['Freios ABS', 'Câmera de estacionamento', 'Câ...",77836.23
Cielo Hatch,Motor Diesel,2019,NaN,True,"['Painel digital', 'Central multimídia', 'Câme...",145197.70
Symbol,Motor Diesel,2016,117714.0,False,"['4 X 4', 'Piloto automático', 'Sensor crepusc...",133030.60
A4 Sedan,Motor Diesel,2002,30511.0,False,"['Câmera de estacionamento', '4 X 4', 'Travas ...",96369.04
A4 Avant,Motor Diesel,2014,17357.0,False,"['Teto panorâmico', '4 X 4', 'Bancos de couro'...",138946.88
Silver Shadow,Motor Diesel,2015,99052.0,False,"['4 X 4', 'Central multimídia', 'Ar condiciona...",143568.22
Camry,Motor Diesel,2019,NaN,True,"['Travas elétricas', 'Rodas de liga', 'Sensor ...",138597.27
Clio,Motor Diesel,1990,66437.0,False,"['4 X 4', 'Câmbio automático', 'Freios ABS', '...",111130.33
Série 3 M3 Coupé,Motor Diesel,2013,19896.0,False,"['Bancos de couro', 'Sensor de chuva', 'Ar con...",69219.89
Gallardo LP 560 – 4,Motor Diesel,2000,113045.0,False,"['Freios ABS', 'Teto panorâmico', 'Central mul...",144118.91
Chana Utility,Motor Diesel,2009,52034.0,False,"['Ar condicionado', 'Sensor de estacionamento'...",132662.32
TT Roadster,Motor Diesel,1998,107392.0,False,"['Ar condicionado', 'Sensor de estacionamento'...",85311.40
Aston Martin Virage,Motor Diesel,2019,NaN,True,"['Travas elétricas', 'Controle de tração', 'Câ...",97290.18
Sandero,Motor Diesel,2015,34783.0,False,"['Piloto automático', 'Teto panorâmico', 'Câmb...",112350.61
XKR,Motor Diesel,1996,85127.0,False,"['Controle de tração', 'Ar condicionado', 'Tra...",54263.16
X5,Motor Diesel,2002,13606.0,False,"['Controle de tração', 'Piloto automático', 'T...",62041.32
Dodge Dakota,Motor Diesel,1993,71544.0,False,"['Controle de tração', 'Sensor de estacionamen...",141083.35
i30 CW,Motor Diesel,2015,8497.0,False,"['Sensor de chuva', 'Vidros elétricos', 'Contr...",73311.75
Série 7 Sedã,Motor Diesel,2019,NaN,True,"['Vidros elétricos', 'Travas elétricas', 'Roda...",67539.79
V60,Motor Diesel,2004,91840.0,False,"['Rodas de liga', 'Sensor crepuscular', 'Ar co...",114728.74
Aston Martin DB5,Motor Diesel,1996,7685.0,False,"['Ar condicionado', '4 X 4', 'Câmbio automátic...",122110.90

In [89]:
dataset[(select) & (dataset.Zero_km == True)]

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Sorento,Motor Diesel,2019,NaN,True,"['Sensor de chuva', 'Câmera de estacionamento'...",81399.35
Cielo Hatch,Motor Diesel,2019,NaN,True,"['Painel digital', 'Central multimídia', 'Câme...",145197.70
Camry,Motor Diesel,2019,NaN,True,"['Travas elétricas', 'Rodas de liga', 'Sensor ...",138597.27
Aston Martin Virage,Motor Diesel,2019,NaN,True,"['Travas elétricas', 'Controle de tração', 'Câ...",97290.18
Série 7 Sedã,Motor Diesel,2019,NaN,True,"['Vidros elétricos', 'Travas elétricas', 'Roda...",67539.79

### Utilizando o método Query

In [92]:
dataset.query('Motor == "Motor Diesel" and Zero_km')

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Sorento,Motor Diesel,2019,NaN,True,"['Sensor de chuva', 'Câmera de estacionamento'...",81399.35
Cielo Hatch,Motor Diesel,2019,NaN,True,"['Painel digital', 'Central multimídia', 'Câme...",145197.70
Camry,Motor Diesel,2019,NaN,True,"['Travas elétricas', 'Rodas de liga', 'Sensor ...",138597.27
Aston Martin Virage,Motor Diesel,2019,NaN,True,"['Travas elétricas', 'Controle de tração', 'Câ...",97290.18
Série 7 Sedã,Motor Diesel,2019,NaN,True,"['Vidros elétricos', 'Travas elétricas', 'Roda...",67539.79

## Iterando nos DataFrames

In [96]:
for item in dataset:
  print(item)

# faz iteração por coluna

Motor
Ano
Quilometragem
Zero_km
Valor

In [98]:
for index, row in dataset.iterrows():
  if (2019 - row['Ano']) != 0:
    dataset.loc[index, 'Km_media'] = row['Quilometragem'] / (2019 - row['Ano'])
  else: 
    dataset.loc[index, 'Km_media'] = 0

dataset

                    Motor   Ano  Quilometragem  Zero_km     Valor     Km_media
Jetta     Motor 4.0 Turbo  2019            0.0     True   88000.0     0.000000
Passat       Motor Diesel  2003         5712.0    False  106000.0   357.000000
Crossfox  Motor Diesel V8  1991        37123.0    False   72000.0  1325.821429
DS5          Motor Diesel  2019            0.0     True   89000.0     0.000000
Fusca           Motor 1.6  1990       120000.0    False   32000.0  4137.931034

## Tratamento de dados

In [100]:
dataset = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Python para Data Science/03_pandas/data/db.csv', 
                      sep = ';', index_col = 'Nome')
dataset

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"['Rodas de liga', 'Travas elétricas', 'Piloto ...",88078.64
Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94
Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Controle de estabilidad...",72832.16
DS5,Motor 2.4 Turbo,2019,NaN,True,"['Travas elétricas', '4 X 4', 'Vidros elétrico...",124549.07
Aston Martin DB4,Motor 2.4 Turbo,2006,25757.0,False,"['Rodas de liga', '4 X 4', 'Central multimídia...",92612.10
...,...,...,...,...,...,...
Phantom 2013,Motor V8,2014,27505.0,False,"['Controle de estabilidade', 'Piloto automátic...",51759.58
Cadillac Ciel concept,Motor V8,1991,29981.0,False,"['Bancos de couro', 'Painel digital', 'Sensor ...",51667.06
Classe GLK,Motor 5.0 V8 Bi-Turbo,2002,52637.0,False,"['Rodas de liga', 'Controle de tração', 'Câmbi...",68934.03
Aston Martin DB5,Motor Diesel,1996,7685.0,False,"['Ar condicionado', '4 X 4', 'Câmbio automátic...",122110.90
Macan,Motor Diesel V6,1992,50188.0,False,"['Central multimídia', 'Teto panorâmico', 'Vid...",90381.47

In [101]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 258 entries, Jetta Variant to Macan
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Motor          258 non-null    object
 1   Ano            258 non-null    int64
 2   Quilometragem  197 non-null    float64
 3   Zero_km        258 non-null    bool
 4   Acessórios     258 non-null    object
 5   Valor          258 non-null    float64
dtypes: bool(1), float64(2), int64(1), object(2)
memory usage: 20.4+ KB

In [103]:
dataset.Quilometragem.isna()

Nome
Jetta Variant            False
Passat                   False
Crossfox                 False
DS5                       True
Aston Martin DB4         False
                         ...
Phantom 2013             False
Cadillac Ciel concept    False
Classe GLK               False
Aston Martin DB5         False
Macan                    False
Name: Quilometragem, Length: 258, dtype: bool

### Preenche NA com o valor dado

In [104]:
dataset.fillna(0, inplace = True)

### Remove linhas com NA

In [106]:
dataset = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Python para Data Science/03_pandas/data/db.csv', 
                      sep = ';', index_col = 'Nome')
dataset

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"['Rodas de liga', 'Travas elétricas', 'Piloto ...",88078.64
Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94
Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Controle de estabilidad...",72832.16
DS5,Motor 2.4 Turbo,2019,NaN,True,"['Travas elétricas', '4 X 4', 'Vidros elétrico...",124549.07
Aston Martin DB4,Motor 2.4 Turbo,2006,25757.0,False,"['Rodas de liga', '4 X 4', 'Central multimídia...",92612.10
...,...,...,...,...,...,...
Phantom 2013,Motor V8,2014,27505.0,False,"['Controle de estabilidade', 'Piloto automátic...",51759.58
Cadillac Ciel concept,Motor V8,1991,29981.0,False,"['Bancos de couro', 'Painel digital', 'Sensor ...",51667.06
Classe GLK,Motor 5.0 V8 Bi-Turbo,2002,52637.0,False,"['Rodas de liga', 'Controle de tração', 'Câmbi...",68934.03
Aston Martin DB5,Motor Diesel,1996,7685.0,False,"['Ar condicionado', '4 X 4', 'Câmbio automátic...",122110.90
Macan,Motor Diesel V6,1992,50188.0,False,"['Central multimídia', 'Teto panorâmico', 'Vid...",90381.47

In [109]:
dataset.dropna(subset = ['Quilometragem'], inplace = True)

In [110]:
dataset

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"['Rodas de liga', 'Travas elétricas', 'Piloto ...",88078.64
Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94
Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Controle de estabilidad...",72832.16
Aston Martin DB4,Motor 2.4 Turbo,2006,25757.0,False,"['Rodas de liga', '4 X 4', 'Central multimídia...",92612.10
Palio Weekend,Motor 1.8 16v,2012,10728.0,False,"['Sensor de estacionamento', 'Teto panorâmico'...",97497.73
...,...,...,...,...,...,...
Phantom 2013,Motor V8,2014,27505.0,False,"['Controle de estabilidade', 'Piloto automátic...",51759.58
Cadillac Ciel concept,Motor V8,1991,29981.0,False,"['Bancos de couro', 'Painel digital', 'Sensor ...",51667.06
Classe GLK,Motor 5.0 V8 Bi-Turbo,2002,52637.0,False,"['Rodas de liga', 'Controle de tração', 'Câmbi...",68934.03
Aston Martin DB5,Motor Diesel,1996,7685.0,False,"['Ar condicionado', '4 X 4', 'Câmbio automátic...",122110.90
Macan,Motor Diesel V6,1992,50188.0,False,"['Central multimídia', 'Teto panorâmico', 'Vid...",90381.47